name: Test Cartesify
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Download nonodo binary
        run: |
          mkdir -p bin
          curl -L -o bin/nonodo.tar.gz https://github.com/gligneul/nonodo/releases/download/v0.1.0/nonodo-v0.1.0-linux-amd64.tar.gz
          tar -xzf bin/nonodo.tar.gz -C bin
          rm bin/nonodo.tar.gz

      - name: Run nonodo in background
        run: |
          cd bin
          nohup ./nonodo &

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: "npm"
      - name: Run deroll in background
        run: |
          cd backend-example
          yarn install
          yarn add express
          nohup yarn start &
          nohup node expressjs/app.js &
          cd ..
          npm ci
          npm run test -- --bail --forceExit
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
