name: Cartesify CI
on:
  push:
    branches:
      - "**"
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install brunodo
        run: |
          npm i -g nonodo@1.2.1

      - name: Run nonodo in background
        run: |
          export PACKAGE_NONODO_VERSION=1.0.0
          nohup nonodo &

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: Run deroll in background
        run: |
          cd cartesify-backend/example
          npm ci
          nohup node app.js &
          cd -
          pnpm install --frozen-lockfile
          pnpm run wagmi
          pnpm run test:ci
          pnpm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"
      - name: Publish
        run: |
          pnpm install --frozen-lockfile
          pnpm run wagmi
          pnpm run build
          pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
