name: Cartesify CI
on:
  push:
    branches:
      - "**"
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Install brunodo
        run: |
          npm i -g nonodo@1.2.5

      - name: Run nonodo in background
        run: |
          export PACKAGE_NONODO_VERSION=1.0.0
          nohup nonodo &

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: Run deroll in background
        run: |
          cd cartesify-backend/example
          npm ci
          nohup node app.js &
          cd -
          corepack pnpm install --frozen-lockfile
          corepack pnpm run wagmi
          corepack pnpm run test:ci
          corepack pnpm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          registry-url: "https://registry.npmjs.org"
      - name: Publish
        run: |
          corepack pnpm install --frozen-lockfile
          corepack pnpm run wagmi
          corepack pnpm run build
          corepack pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
